"""add confessions table

Revision ID: 74222d783e0e
Revises: fa6c26a70384
Create Date: 2026-04-22 03:46:10.202318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from uuid_extensions import uuid7  # type: ignore[import-untyped]


# revision identifiers, used by Alembic.
revision: str = "74222d783e0e"
down_revision: Union[str, Sequence[str], None] = "fa6c26a70384"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "confessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.String(length=2000), nullable=False),
        sa.Column("authored_by", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    confession_element_id = uuid7()
    admin_perm_id = uuid7()
    user_perm_id = uuid7()

    # Add "confession"
    op.execute(
        f"INSERT INTO business_elements (id, name, description) "
        f"VALUES ('{confession_element_id}', 'confession', 'Confessions management')"
    )

    # Admin permissions
    op.execute(
        f"INSERT INTO permissions (id, business_element_id, read_permission, read_all_permission, "
        f"create_permission, update_permission, update_all_permission, delete_permission, "
        f"delete_all_permission, description) VALUES ("
        f"'{admin_perm_id}', '{confession_element_id}', "
        f"true, true, true, true, true, true, true, 'Full access to confessions')"
    )

    # User: (create/read all, update/delete own)
    op.execute(
        f"INSERT INTO permissions (id, business_element_id, read_permission, read_all_permission, "
        f"create_permission, update_permission, update_all_permission, delete_permission, "
        f"delete_all_permission, description) VALUES ("
        f"'{user_perm_id}', '{confession_element_id}', "
        f"true, true, true, true, false, true, false, 'User confessions access')"
    )

    # Assigning permissions to existing roles
    op.execute(
        f"INSERT INTO role_permissions (role_id, permission_id) "
        f"SELECT id, '{admin_perm_id}' FROM roles WHERE name = 'admin'"
    )
    op.execute(
        f"INSERT INTO role_permissions (role_id, permission_id) "
        f"SELECT id, '{user_perm_id}' FROM roles WHERE name = 'user'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM business_elements WHERE name = 'confession'")
    op.drop_table("confessions")
    # ### end Alembic commands ###
